#Au rămas două valori cu semn de întrebare în loc de diacritice, sunt erori
#necorectate de la instalarea GIT

# #Aici am început să corectez denumirile localităţilor de la parlamentare
# #în funcţie de ortografia de la referendum, dar pe urmă mi-am dat seama
# #că pot folosi codul Siruta ca cheie comună şi nu am continuat.
# a.par[a.par$DEN_CIRC == "ORAS CIMPENI",][4] <- "ORAS CAMPENI"
# a.par[a.par$DEN_CIRC == "CERU BACAINTI",][4] <- "CERU-BACAINTI"
# a.par[a.par$DEN_CIRC == "GIRBOVA",][4] <- "GARBOVA"
# a.par[a.par$DEN_CIRC == "GIRDA DE SUS",][4] <- "GARDA DE SUS"
# a.par[a.par$DEN_CIRC == "HOPIRTA",][4] <- "HOPARTA"
# a.par[a.par$DEN_CIRC == "SINCEL",][4] <- "SANCEL"
# a.par[a.par$DEN_CIRC == "BELETI-NEGRESTI",][4] <- "BELETI ? NEGRESTI"
# a.par[a.par$DEN_CIRC == "CAPILNA",][4] <- "CAPALNA"
# a.par[a.par$DEN_CIRC == "CIMPANI",][4] <- "CAMPANI"
# a.par[a.par$DEN_CIRC == "SIMBATA",][4] <- "SAMBATA"
# a.par[a.par$DEN_CIRC == "SINNICOLAU ROMAN",][4] <- "SANNICOLAU ROMAN"
# a.par[a.par$DEN_CIRC == "MUNICIPIUL CAMPIA-TURZII",][4] <- "MUNICIPIUL CAMPIA TURZII"
# a.par[a.par$DEN_CIRC == "MAGURI RACATAU",][4] <- "MAGURI-RACATAU"
# a.par[a.par$DEN_CIRC == "GIURGIU",][4] <- "MUNICIPIUL GIURGIU"
# a.par[a.par$DEN_CIRC == "BOLINTIN-VALE",][4] <- "ORAS BOLINTIN-VALE"
# a.par[a.par$DEN_CIRC == "CAPILNITA",][4] <- "CAPALNITA"
# a.par[a.par$DEN_CIRC == "CIUCSINGEORGIU",][4] <- "CIUCSANGEORGIU"
# a.par[a.par$DEN_CIRC == "MUNTENI BUZAU",][4] <- "MUNTENI-BUZAU"
# a.par[a.par$DEN_CIRC == "ALEXANDRU IOAN CUZA",][4] <- "ALEXANDRU I. CUZA"
# a.par[a.par$DEN_CIRC == "BAIA MARE",][4] <- "MUNICIPIUL BAIA MARE"
# a.par[a.par$DEN_CIRC == "SIGHETU MARMATIEI",][4] <- "MUNICIPIUL SIGHETU MARMATIEI"
# a.par[a.par$DEN_CIRC == "BAIA SPRIE",][4] <- "ORAS BAIA SPRIE"
# a.par[a.par$DEN_CIRC == "CAVNIC",][4] <- "ORAS CAVNIC"
# a.par[a.par$DEN_CIRC == "SALISTEA DE SUS",][4] <- "ORAS SALISTEA DE SUS"
# a.par[a.par$DEN_CIRC == "SEINI",][4] <- "ORAS SEINI"
# a.par[a.par$DEN_CIRC == "SOMCUTA MARE",][4] <- "ORAS SOMCUTA MARE"
# a.par[a.par$DEN_CIRC == "TAUTII MAGHERAUS",][4] <- "ORAS TAUTII-MAGHERAUS"
# a.par[a.par$DEN_CIRC == "TARGU LAPUS",][4] <- "ORAS TARGU LAPUS"
# a.par[a.par$DEN_CIRC == "VISEU DE SUS",][4] <- "ORAS VISEU DE SUS"
# a.par[a.par$DEN_CIRC == "COPALNIC MANASTUR",][4] <- "COPALNIC-MANASTUR"
# a.par[a.par$DEN_CIRC == "FILIPESTII DE TIRG",][4] <- "FILIPESTII DE TARG"
# a.par[a.par$DEN_CIRC == "SINGERU",][4] <- "SANGERU"
# a.par[a.par$DEN_CIRC == "TIRGSORU VECHI",][4] <- "TARGSORU VECHI"
# a.par[a.par$DEN_CIRC == "VILCANESTI",][4] <- "VALCANESTI"
# a.par[a.par$DEN_CIRC == "MUNICIPIUL ROSIORII DE VEDE",][4] <- "MUNICIPIUL ROSIORI DE VEDE"
# a.par[a.par$DEN_CIRC == "DUDA EPURENI",][4] <- "DUDA-EPURENI"
# a.par[a.par$DEN_CIRC == "CAINENI",][4] <- "CIINENI"
# a.par[a.par$DEN_CIRC == "CRE_ENI",][4] <- "CRETENI"
# a.par[a.par$DEN_CIRC == "FARTA_ESTI",][4] <- "FIRTATESTI"
# a.par[a.par$DEN_CIRC == "ORASUL MARASESTI",][4] <- "ORAS MARASESTI"
# a.par[a.par$DEN_CIRC == "ORASUL ODOBESTI",][4] <- "ORAS ODOBESTI"
# a.par[a.par$DEN_CIRC == "ORASUL PANCIU",][4] <- "ORAS PANCIU"
# a.par[a.par$DEN_CIRC == "CORBI_A",][4] <- "CORBITA"
# a.par[a.par$DEN_CIRC == "GURA CALI_EI",][4] <- "GURA CALITEI"
# a.par[a.par$DEN_CIRC == "OBREJI_A",][4] <- "OBREJITA"
# a.par[a.par$DEN_CIRC == "PLOSCU_ENI",][4] <- "PLOSCUTENI"
# a.par[a.par$DEN_CIRC == "_IFESTI",][4] <- "TIFESTI"
# a.par[a.par$DEN_CIRC == "MUNICIPIUL BUCURESTI SECTORUL 1",][4] <- "BUCURESTI SECTOR 1"
# a.par[a.par$DEN_CIRC == "MUNICIPIUL BUCURESTI SECTORUL 2",][4] <- "BUCURESTI SECTOR 2"
# a.par[a.par$DEN_CIRC == "MUNICIPIUL BUCURESTI SECTORUL 3",][4] <- "BUCURESTI SECTOR 3"
# a.par[a.par$DEN_CIRC == "MUNICIPIUL BUCURESTI SECTORUL 4",][4] <- "BUCURESTI SECTOR 4"
# a.par[a.par$DEN_CIRC == "MUNICIPIUL BUCURESTI SECTORUL 5",][4] <- "BUCURESTI SECTOR 5"
# a.par[a.par$DEN_CIRC == "MUNICIPIUL BUCURESTI SECTORUL 6",][4] <- "BUCURESTI SECTOR 6"
# a.par[a.par$DEN_CIRC == "RIMETEA",][4] <- "RAMETEA"
# a.par[a.par$DEN_CIRC == "RIMET",][4] <- "RAMET"
# a.par[a.par$DEN_CIRC == "COMANDAU",][4] <- "COMAND?U"
# #Denumire comună schimbată complet
# a.par[a.par$DEN_CIRC == "SANIOB",][4] <- "CIUHOI"